// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of change made to a file.
 */
export type ChangeType = "Added" | "Modified" | "Deleted" | "Restored";
