// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CRDT history entry for version tracking.
 */
export type CrdtHistoryEntry = { 
/**
 * Update ID.
 */
update_id: bigint, 
/**
 * Timestamp of the update (Unix milliseconds).
 */
timestamp: bigint, 
/**
 * Origin of the update.
 */
origin: string, 
/**
 * Files that were changed in this update.
 */
files_changed: Array<string>, 
/**
 * Device ID that created this update (for multi-device attribution).
 */
device_id: string | null, 
/**
 * Human-readable device name.
 */
device_name: string | null, };
