// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CRDT history entry for version tracking.
 */
export type CrdtHistoryEntry = { 
/**
 * Update ID.
 */
update_id: bigint, 
/**
 * Timestamp of the update (Unix milliseconds).
 */
timestamp: bigint, 
/**
 * Origin of the update.
 */
origin: string, };
