// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateEntryOptions = { 
/**
 * Title for the entry.
 */
title: string | null, 
/**
 * Parent to attach to.
 */
part_of: string | null, 
/**
 * Template to use.
 */
template: string | null, };
