// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of creating a child entry, with details about any parent conversion.
 *
 * When creating a child under a leaf file, the leaf is converted to an index first.
 * This struct provides both the new child path and the (possibly new) parent path,
 * allowing the frontend to correctly update the tree and navigation.
 */
export type CreateChildResult = {
/**
 * Path to the newly created child entry.
 */
child_path: string,
/**
 * Current path to the parent entry (may differ from input if converted to index).
 */
parent_path: string,
/**
 * True if the parent was converted from a leaf to an index.
 */
parent_converted: boolean,
/**
 * Original parent path before conversion (only set if parent_converted is true).
 */
original_parent_path: string | null, };
