// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExclusionReason } from "./ExclusionReason";

/**
 * A file that was excluded from export
 */
export type ExcludedFile = { 
/**
 * Path to the excluded file
 */
path: string, 
/**
 * Reason for exclusion
 */
reason: ExclusionReason, };
