// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportedFile = { 
/**
 * Relative path.
 */
path: string, 
/**
 * File content.
 */
content: string, };
