// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExcludedFile } from "./ExcludedFile";
import type { ExportFile } from "./ExportFile";

/**
 * Result of planning an export operation
 */
export type ExportPlan = { 
/**
 * Files that will be exported
 */
included: Array<ExportFile>, 
/**
 * Files that were filtered out (with reason)
 */
excluded: Array<ExcludedFile>, 
/**
 * The audience being exported for
 */
audience: string, 
/**
 * Source workspace root
 */
source_root: string, 
/**
 * Destination directory
 */
destination: string, };
