// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file to be exported
 */
export type ExportFile = { 
/**
 * Original path in the workspace
 */
source_path: string, 
/**
 * Path relative to workspace root
 */
relative_path: string, 
/**
 * Destination path
 */
dest_path: string, 
/**
 * Contents entries that will be filtered out (if any)
 */
filtered_contents: Array<string>, };
