// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMatch } from "./SearchMatch";

/**
 * Search results for a single file
 */
export type FileSearchResult = { 
/**
 * Path to the file
 */
path: string, 
/**
 * Title from frontmatter (if available)
 */
title: string | null, 
/**
 * All matches found in this file
 */
matches: Array<SearchMatch>, };
