// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeType } from "./ChangeType";
import type { FileMetadata } from "./FileMetadata";

/**
 * Difference between two versions of a file.
 */
export type FileDiff = { 
/**
 * Path to the file
 */
path: string, 
/**
 * Type of change
 */
change_type: ChangeType, 
/**
 * Metadata before the change (None if file was added)
 */
old_metadata: FileMetadata | null, 
/**
 * Metadata after the change (None if file was removed)
 */
new_metadata: FileMetadata | null, };
