// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of attempting to fix a validation issue.
 */
export type FixResult = { 
/**
 * Whether the fix was successful.
 */
success: boolean, 
/**
 * Description of what was done (or why it failed).
 */
message: string, };
