// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for guest mode sync.
 *
 * Guests need special path handling to isolate their storage from the host.
 */
export type GuestConfig = {
/**
 * The join code for the share session.
 */
join_code: string,
/**
 * If true, prefix paths with guest/{join_code}/ for OPFS storage.
 * If false (in-memory storage), paths are used as-is.
 */
uses_opfs: boolean, };
