// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A history entry with metadata about what changed.
 */
export type HistoryEntry = { 
/**
 * Unique update ID
 */
update_id: bigint, 
/**
 * Unix timestamp (milliseconds)
 */
timestamp: bigint, 
/**
 * Origin of the change
 */
origin: string, 
/**
 * Files that were changed in this update (if determinable)
 */
files_changed: Array<string>, 
/**
 * Device ID that created this update (for multi-device attribution)
 */
device_id: string | null, 
/**
 * Human-readable device name (e.g., "MacBook Pro", "iPhone")
 */
device_name: string | null, };
