// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The format to use when writing links to frontmatter.
 *
 * This controls how `part_of` and `contents` paths are serialized.
 */
export type LinkFormat = "markdown_root" | "markdown_relative" | "plain_relative" | "plain_canonical";
