// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AncestorAttachmentsResult } from "./AncestorAttachmentsResult";
import type { BinaryExportFile } from "./BinaryExportFile";
import type { BinaryFileInfo } from "./BinaryFileInfo";
import type { ConvertLinksResult } from "./ConvertLinksResult";
import type { CreateChildResult } from "./CreateChildResult";
import type { EntryData } from "./EntryData";
import type { ExportPlan } from "./ExportPlan";
import type { ExportedFile } from "./ExportedFile";
import type { FixResult } from "./FixResult";
import type { FixSummary } from "./FixSummary";
import type { JsonValue } from "../serde_json/JsonValue";
import type { LinkFormat } from "./LinkFormat";
import type { SearchResults } from "./SearchResults";
import type { StorageInfo } from "./StorageInfo";
import type { TemplateInfo } from "./TemplateInfo";
import type { TreeNode } from "./TreeNode";
import type { ValidationResultWithMeta } from "./ValidationResultWithMeta";
import type { WorkspaceConfig } from "./WorkspaceConfig";

/**
 * Response from a command execution.
 */
export type Response = { "type": "Ok" } | { "type": "String", "data": string } | { "type": "Bool", "data": boolean } | { "type": "Entry", "data": EntryData } | { "type": "Tree", "data": TreeNode } | { "type": "Frontmatter", "data": { [key in string]?: JsonValue } } | { "type": "SearchResults", "data": SearchResults } | { "type": "ValidationResult", "data": ValidationResultWithMeta } | { "type": "FixResult", "data": FixResult } | { "type": "FixSummary", "data": FixSummary } | { "type": "ExportPlan", "data": ExportPlan } | { "type": "ExportedFiles", "data": Array<ExportedFile> } | { "type": "BinaryFiles", "data": Array<BinaryExportFile> } | { "type": "BinaryFilePaths", "data": Array<BinaryFileInfo> } | { "type": "Templates", "data": Array<TemplateInfo> } | { "type": "Strings", "data": Array<string> } | { "type": "Bytes", "data": Array<number> } | { "type": "StorageInfo", "data": StorageInfo } | { "type": "AncestorAttachments", "data": AncestorAttachmentsResult } | { "type": "LinkFormat", "data": LinkFormat } | { "type": "WorkspaceConfig", "data": WorkspaceConfig } | { "type": "ConvertLinksResult", "data": ConvertLinksResult } | { "type": "CreateChildResult", "data": CreateChildResult };
