// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageInfo = { 
/**
 * Bytes used.
 */
used: bigint, 
/**
 * Storage limit (if any).
 */
limit: bigint | null, 
/**
 * Attachment size limit.
 */
attachment_limit: bigint | null, };
