// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateInfo = { 
/**
 * Template name.
 */
name: string, 
/**
 * Path to template file (None for built-in).
 */
path: string | null, 
/**
 * Source of the template.
 */
source: string, };
