// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationError } from "./ValidationError";
import type { ValidationWarning } from "./ValidationWarning";

/**
 * Result of validating a workspace.
 */
export type ValidationResult = { 
/**
 * Validation errors (broken references)
 */
errors: Array<ValidationError>, 
/**
 * Validation warnings (orphans, cycles)
 */
warnings: Array<ValidationWarning>, 
/**
 * Number of files checked
 */
files_checked: number, };
