// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkFormat } from "./LinkFormat";

/**
 * Workspace-level configuration stored in the root index file's frontmatter.
 *
 * This allows workspace settings to live with the data (local-first philosophy)
 * rather than in separate config files.
 */
export type WorkspaceConfig = {
/**
 * Format for `part_of` and `contents` links.
 * Defaults to MarkdownRoot if not specified.
 */
link_format: LinkFormat,
/**
 * Subfolder for daily entries (e.g., "Daily" or "Journal/Daily").
 * If not specified, daily entries are created at workspace root.
 */
daily_entry_folder: string | null, };
